-
  name: install and run appache
  hosts: server_2
  become: yes
  tasks:
    - name: install appache
      apt:
        name: apache2
        state: latest
        update_cache: yes
    - name: run the service
      service:
        name: apache2
        state: started
        enabled: yes
